version: '3.8'
services:
  container:
    build: .
    image: csci4145-chatapp:latest
    container_name: chatapp
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - chatapp_network

networks:
  chatapp_network:
    driver: bridge
